services:
  bot:
    build: .
    container_name: discord-bot
    restart: always
    volumes:
      - .:/app
    depends_on:
      - voicebox

  voicebox:
    image: voicevox/voicevox_engine:cpu-latest
    container_name: voicebox
    ports:
      - "50021:50021"
